/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-01-19")
public enum OperationMode implements org.apache.thrift.TEnum {
  kManual(0),
  kAuto(1),
  kRemote(2);

  private final int value;

  private OperationMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static OperationMode findByValue(int value) { 
    switch (value) {
      case 0:
        return kManual;
      case 1:
        return kAuto;
      case 2:
        return kRemote;
      default:
        return null;
    }
  }
}
