/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-01-19")
public enum SafetyState implements org.apache.thrift.TEnum {
  SS_INIT(0),
  SS_WAIT(2),
  SS_CONFIG(3),
  SS_POWER_OFF(4),
  SS_RUN(5),
  SS_RECOVERY(6),
  SS_STOP2(7),
  SS_STOP1(8),
  SS_STOP0(9),
  SS_MODEL(10),
  SS_REDUCE(12),
  SS_BOOT(13),
  SS_FAIL(14),
  SS_UPDATE(99);

  private final int value;

  private SafetyState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SafetyState findByValue(int value) { 
    switch (value) {
      case 0:
        return SS_INIT;
      case 2:
        return SS_WAIT;
      case 3:
        return SS_CONFIG;
      case 4:
        return SS_POWER_OFF;
      case 5:
        return SS_RUN;
      case 6:
        return SS_RECOVERY;
      case 7:
        return SS_STOP2;
      case 8:
        return SS_STOP1;
      case 9:
        return SS_STOP0;
      case 10:
        return SS_MODEL;
      case 12:
        return SS_REDUCE;
      case 13:
        return SS_BOOT;
      case 14:
        return SS_FAIL;
      case 99:
        return SS_UPDATE;
      default:
        return null;
    }
  }
}
