/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-01-19")
public enum StateProgram implements org.apache.thrift.TEnum {
  SP_Stopped(0),
  SP_Stopping(1),
  SP_Running(2),
  SP_Paused(3),
  SP_Pausing(4);

  private final int value;

  private StateProgram(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static StateProgram findByValue(int value) { 
    switch (value) {
      case 0:
        return SP_Stopped;
      case 1:
        return SP_Stopping;
      case 2:
        return SP_Running;
      case 3:
        return SP_Paused;
      case 4:
        return SP_Pausing;
      default:
        return null;
    }
  }
}
