/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum SafetyState
{
  SS_INIT = 0,
  SS_WAIT = 2,
  SS_CONFIG = 3,
  SS_POWER_OFF = 4,
  SS_RUN = 5,
  SS_RECOVERY = 6,
  SS_STOP2 = 7,
  SS_STOP1 = 8,
  SS_STOP0 = 9,
  SS_MODEL = 10,
  SS_REDUCE = 12,
  SS_BOOT = 13,
  SS_FAIL = 14,
  SS_UPDATE = 99,
}
