/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum StateRobot
{
  SR_Start = 0,
  SR_Initialize = 1,
  SR_Logout = 2,
  SR_Login = 3,
  SR_PowerOff = 4,
  SR_Disable = 5,
  SR_Enable = 6,
}
