/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum StateProgram
{
  SP_Stopped = 0,
  SP_Stopping = 1,
  SP_Running = 2,
  SP_Paused = 3,
  SP_Pausing = 4,
}
