/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TaskState
{
  ST_Idle = 0,
  ST_Running = 1,
  ST_Paused = 2,
  ST_Stopped = 3,
  ST_Finished = 4,
  ST_Interrupt = 5,
  ST_Error = 6,
  ST_Illegal = 7,
  ST_ParameterMismatch = 8,
}
